# Generated by Django 3.0.7 on 2020-07-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='is_verify'),
        ),
    ]
